FROM node:22-alpine

WORKDIR /app

# Install dependencies
COPY package.json package-lock.json ./
RUN npm ci

# Copy source code
COPY . .

# Argument to define which app to build
ARG APP_NAME

# Build the specified app
RUN npm run build ${APP_NAME}

# Set environment variable so the app knows its name
ENV APP_MAIN_FILE=dist/apps/${APP_NAME}/main.js

# Expose ports will be done in docker-compose.yml

CMD ["sh", "-c", "node $APP_MAIN_FILE"]
